title: NorthernBUG
# author: GitHub User
# email: your-email@domain.com
description: > # this means to ignore newlines until "twitter_username:"
  A network of bioinformaticians and users or bioinformatics services in the north of England. Inspired by NextGenBUG
  we hold quarterly meetings to build a community of researchers and others using big data in biology.

# social links
# twitter_username: jekyllrb
github_username:  NorthernBUG
# rss: rss
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: jekyll
# linkedin_username: jekyll
# pinterest_username: jekyll
# youtube_username: jekyll
# googleplus_username: +jekyll
googlegroups_username: northern-bug

# Mastodon instances
# mastodon:
# - username: jekyll
#   instance: example.com
# - username: jekyll2
#   instance: example.com


show_excerpts: true # set to true to show excerpts on the homepage

# Minima date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
minima:
  date_format: "%b %-d, %Y"

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
header_pages:
 - about.md
 - contact.md
 - meetings.md
 - members.md
 - resources.md

# Build settings
theme: minima

plugins:
 - jekyll-feed
 - jekyll-seo-tag
 - jekyll-avatar
